"""All ORM models. Importing this package registers every table on ``Base``."""
from __future__ import annotations

from diagold.db.models.base import Base
from diagold.db.models.auth import (
    Role,
    RolePermission,
    User,
    UserPermission,
    hash_password,
    verify_password,
)
from diagold.db.models.master import (
    Account,
    Colour,
    Company,
    Currency,
    DailyLabourRate,
    DailyMetalRate,
    DefaultProcessStep,
    FamilyCategory,
    Finding,
    LabourRate,
    Location,
    LocationMaterial,
    ManufacturingProcess,
    Metal,
    MetalRatio,
    MetalVendor,
    MouldModification,
    MarginComponent,
    MarginSet,
    OtherSetting,
    PartMould,
    ProcessCheckpoint,
    SettingLabourRate,
    SettingType,
    SettingWork,
    SkuInfo,
    StoneInfo,
)
from diagold.db.models.sku import ProductSku, ProductSkuStone, StoneSku

__all__ = [
    "Base",
    "Role",
    "RolePermission",
    "User",
    "UserPermission",
    "hash_password",
    "verify_password",
    "Account",
    "Colour",
    "Company",
    "Currency",
    "DailyLabourRate",
    "DailyMetalRate",
    "DefaultProcessStep",
    "FamilyCategory",
    "Finding",
    "LabourRate",
    "Location",
    "LocationMaterial",
    "ManufacturingProcess",
    "Metal",
    "MetalRatio",
    "MetalVendor",
    "MouldModification",
    "MarginComponent",
    "MarginSet",
    "OtherSetting",
    "PartMould",
    "ProcessCheckpoint",
    "SettingLabourRate",
    "SettingType",
    "SettingWork",
    "SkuInfo",
    "StoneInfo",
    "ProductSku",
    "ProductSkuStone",
    "StoneSku",
]
