"""All ORM models. Importing this package registers every table on ``Base``."""
from __future__ import annotations

from diagold.db.models.base import Base
from diagold.db.models.auth import (
    Role,
    RolePermission,
    User,
    UserPermission,
    hash_password,
    verify_password,
)
from diagold.db.models.master import (
    Account,
    Colour,
    Company,
    Currency,
    DailyLabourRate,
    DailyMetalRate,
    DefaultProcessStep,
    FamilyCategory,
    Finding,
    LabourRate,
    Location,
    LocationMaterial,
    ManufacturingProcess,
    Metal,
    MetalRatio,
    MetalVendor,
    MouldModification,
    MarginComponent,
    MarginSet,
    OtherSetting,
    PartMould,
    ProcessCheckpoint,
    SettingLabourRate,
    SettingType,
    SettingWork,
    SkuInfo,
    StoneGroup,
    StoneInfo,
    StoneKind,
    StoneQuality,
    StoneShape,
    StoneSize,
)
from diagold.db.models.inventory import AccountEntry, InvVoucher, InvVoucherLine
from diagold.db.models.sales import ReadyVoucher, ReadyVoucherLine
from diagold.db.models.transfer import StockTransfer, StockTransferLine
from diagold.db.models.accounts import (AccountGroup, AccountVoucher, AccountVoucherLine,
                                         BillAllocation)
from diagold.db.models.pricing import (PriceChart, PriceChartLabour, PriceChartSetting,
                                        PriceChartStone)
from diagold.db.models.stock_tools import StockRecon, StockReconScan
from diagold.db.models.admin import AuditLog
from diagold.db.models.service import Complaint, ComplaintLine, GatePass
from diagold.db.models.manufacturing import (
    DeletionLog,
    MfgTransfer,
    MfgTransferLine,
    StockItem,
    VoucherAttachment,
)
from diagold.db.models.production import (
    AppSetting,
    InventoryReturn,
    InventoryReturnLine,
    Job,
    JobBagLine,
    JobBagMovement,
    JobComment,
    JobStep,
    JobVoucher,
    MaterialStock,
    Order,
    OrderLine,
    PrintLog,
    PrintTemplate,
    StockMovement,
    StoneIssue,
    StoneIssueLine,
)
from diagold.db.models.sku import (
    Item,
    ItemPriceRange,
    ProductSku,
    ProductSkuStone,
    StonePacket,
    StoneSku,
    StoneSkuVendor,
)

__all__ = [
    "Complaint", "ComplaintLine", "GatePass",
    "AuditLog",
    "StockRecon", "StockReconScan",
    "PriceChart", "PriceChartLabour", "PriceChartSetting", "PriceChartStone",
    "Base",
    "Role",
    "RolePermission",
    "User",
    "UserPermission",
    "hash_password",
    "verify_password",
    "Account",
    "Colour",
    "Company",
    "Currency",
    "DailyLabourRate",
    "DailyMetalRate",
    "DefaultProcessStep",
    "FamilyCategory",
    "Finding",
    "LabourRate",
    "Location",
    "LocationMaterial",
    "ManufacturingProcess",
    "Metal",
    "MetalRatio",
    "MetalVendor",
    "MouldModification",
    "MarginComponent",
    "MarginSet",
    "OtherSetting",
    "PartMould",
    "ProcessCheckpoint",
    "SettingLabourRate",
    "SettingType",
    "SettingWork",
    "SkuInfo",
    "StoneGroup",
    "StoneInfo",
    "StoneKind",
    "StoneQuality",
    "StoneShape",
    "StoneSize",
    "Item",
    "ItemPriceRange",
    "ProductSku",
    "ProductSkuStone",
    "StonePacket",
    "StoneSku",
    "StoneSkuVendor",
    "AppSetting",
    "InventoryReturn",
    "InventoryReturnLine",
    "Job",
    "JobBagLine",
    "JobBagMovement",
    "JobComment",
    "JobStep",
    "JobVoucher",
    "MaterialStock",
    "Order",
    "OrderLine",
    "PrintLog",
    "PrintTemplate",
    "StockMovement",
    "StoneIssue",
    "StoneIssueLine",
    "InvVoucher",
    "InvVoucherLine",
    "AccountEntry",
    "DeletionLog",
    "VoucherAttachment",
    "ReadyVoucher",
    "ReadyVoucherLine",
    "StockTransfer",
    "StockTransferLine",
    "AccountGroup",
    "AccountVoucher",
    "AccountVoucherLine",
    "BillAllocation",
    "MfgTransfer",
    "MfgTransferLine",
    "StockItem",
]
